### ISSUE TITLE
Date coverage year error

### ISSUE THREAD

**Issue by andrewbrazzatti** [redbox-mint/redbox#62]
When a user creates or edits a record they are prompted to add a date range for the dataset in the Date Coverage field under the Coverage tab. 

It is possible to manually type in a year for this date coverage (for example 2000) instead of using the date yyyy-mm-dd format, however any 3-digit years will be met with an invalid date or year error. 

This limits the functionality of this field to describe the data coverage for a dataset (for example, the year 800 cannot be added, but might be a valid period in history to describe a dataset). 

Saving the record will remove the error message and allow a user to progress through the rest of the record to fill in all required fields however it will not allow the record to be progressed to the next stage of review. It also does not state what the error is that needs to be resolved. 

The document attached provides an example of this. Thanks.

**Comment by andrewbrazzatti** [comment]
Issue created in JIRA https://qcifltd.atlassian.net/browse/REDBOX-291

**Comment by DevikaI** [comment]
Hi Andrew, 
                           Could you please take me out of this mailing list. 
 
Thanks,
Devika
 
Date: Mon, 15 Jun 2015 05:06:49 -0700
