### ISSUE TITLE
Logout Behaviour

### ISSUE THREAD

**Issue by dedickinson** [redbox-mint/redbox#7]
After logging out, ReDBox remains on whatever screen it was on. Depending on the screen, you may get an error message regarding access level. Eg.

1. Login as admin
2. Navigate to Admin > Security
3. Logout
4. You will receive an error message: "Sorry, but you need to be logged in as an administrator to use this screen."
5. Suggestion: On logout, consider a) Navigating to the Home screen; and b) Changing the View to Everything.

**Comment by andrewbrazzatti** [comment]
With the new security changes, the user will be redirected to the login page
